### ISSUE TITLE
Segundo o discord do Gloomhaven, versão da Epic não suporta mods.

### ISSUE THREAD

**Issue by LuizMoratelli** [TioFuna/Gloomhaven-PT-BR#1]
Apesar de após rodar o jogo pela 1a vez as pastas no `%APPDATA%` serem criadas, criar uma pasta de `GloomMods` e as demais como explicado para versão da Steam não funciona :(

![image](https://user-images.githubusercontent.com/24661951/192050041-fbec1ec1-7ea0-4e69-a6c5-406b2312c522.png)

https://discord.com/channels/464045190991314944/600943341105840170/1022674030748250164

**Comment by TioFuna** [comment]
Fui eu que perguntei pra eles. Mas obrigado por postar aqui tbm. Vou atualizar as instruções por enquanto. Mas acredito que ainda seja possível, vamos aguardar.
